version: '3'

services:
  django:
    build:
      context: ./project
    ports:
      - "8000:8000"
    volumes:
      - ./project:/app

  vue:
    build:
      context: ./project_vue
    ports:
      - "8080:8080"
    volumes:
      - ./project_vue:/app
